name: Test

on:
  push:
    branches:
      - main
      - "release/**"
      - "!release/**-published"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:     
      - name: Print Configs (Interpolated)
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          [[ $GITHUB_EVENT_NAME = "pull_request" ]] && BRANCH_NAME="${{ github.head_ref }}" || BRANCH_NAME="${{ github.ref_name }}"

          [[ $GITHUB_EVENT_NAME = "pull_request" ]] && COMMIT_MSG="${{ github.event.pull_request.title }}" || COMMIT_MSG=$(echo -e "${{ github.event.head_commit.message }}" | head -n 1)

          PIPELINE_PROJECT_URL="github.com/$GITHUB_REPOSITORY.git"

          echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"
          echo "COMMIT_MSG=$COMMIT_MSG" >> "$GITHUB_ENV"
          echo "PIPELINE_PROJECT_URL=$PIPELINE_PROJECT_URL" >> "$GITHUB_ENV"

          echo "PIPELINE_PROJECT_URL: $PIPELINE_PROJECT_URL"
          echo "PIPELINE_EVENT: $GITHUB_EVENT_NAME"
          echo "PIPELINE_BRANCH_NAME: $BRANCH_NAME"
          echo "PIPELINE_TRIGGER_PERSON: $GITHUB_ACTOR"
          echo "PIPELINE_COMMIT_MSG: $COMMIT_MSG"

      - name: Use environment variable
        run: |
          echo "The value of COMMIT_MSG is $COMMIT_MSG"
          printf 'The result of COMMIT_MSG is %s\n' "$COMMIT_MSG"
