name: Test fix

on:
  push:
    branches:
      - main
      - "release/**"
      - "!release/**-published"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Print Configs
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          [[ $GITHUB_EVENT_NAME = "pull_request" ]] && BRANCH_NAME="$HEAD_REF" || BRANCH_NAME="$REF_NAME"

          PRINTF_RESULT=$(printf '%s\n' "$HEAD_COMMIT_MSG" | awk 'NR==1{sub(/\r$/, ""); print}')
          PRINTF_FIRST_LINE=$(printf '%s\n' "$HEAD_COMMIT_MSG" | awk 'NR>1{exit};1')
          PRINTF_SIMPLE=$(printf '%s\n' "$HEAD_COMMIT_MSG" | awk '{print $1; exit}')
          ECHO_RESULT=$(echo -e "$HEAD_COMMIT_MSG" | head -n 1)
          
          echo "PRINTF_RESULT=$PRINTF_RESULT" >> "$GITHUB_ENV"
          echo "PRINTF_FIRST_LINE=$PRINTF_FIRST_LINE" >> "$GITHUB_ENV"
          echo "PRINTF_SIMPLE=$PRINTF_SIMPLE" >> "$GITHUB_ENV"
          echo "ECHO_RESULT=$ECHO_RESULT" >> "$GITHUB_ENV"

      - name: Use environment variable
        run: |
          printf 'The result of PRINTF_RESULT is %s\n' "$PRINTF_RESULT"
          printf 'The result of PRINTF_FIRST_LINE is %s\n' "$PRINTF_FIRST_LINE"
          printf 'The result of PRINTF_SIMPLE is %s\n' "$PRINTF_SIMPLE"
          printf 'The result of ECHO_RESULT is %s\n' "$ECHO_RESULT"
